### ISSUE TITLE
Change angle direction option.

### ISSUE THREAD

**Issue by raeleus** [Ogmo-Editor-3/OgmoEditor3-CE#104]
The game framework I use implements rotations as angles in degrees with counter clockwise rotation as positive. This is the opposite of the default in Ogmo. Is it possible to add this as an export option in the project? Thank you.

**Comment by AustinEast** [comment]
We probably will stick with just degrees/radians for the available options (once #101 is fixed 😅) for simplicity, but I think this will be a great use case for export scripting once it’s merged in!

**Comment by raeleus** [comment]
Awesome, thank you.
