### ISSUE TITLE
Allow configuring margins on tilesets

### ISSUE THREAD

**Issue by avivbeeri** [Ogmo-Editor-3/OgmoEditor3-CE#113]
I am using a tileset where the graphics are flush to the edges, but each tile is individually seperated by 1 pixel.

I can't use this in Ogmo Editor because when you set the "Tile Seperation" it assumes that you have borders as well.

Would it be possible to add a "tileset margins" option or something to make this configurable?

<img width="1026" alt="Screen Shot 2020-01-29 at 06 50 45" src="https://user-images.githubusercontent.com/1446063/73334146-d0c52d00-4263-11ea-91d9-b651e97a2767.png">
<img width="1024" alt="Screen Shot 2020-01-29 at 06 52 26" src="https://user-images.githubusercontent.com/1446063/73334176-ee929200-4263-11ea-9985-6afef51796b2.png">

**Comment by AustinEast** [comment]
This should be do-able 👍 I probably can't get to it any time soon, but I think a "Tile Margin" setting would be nice feature to have.

**Comment by AustinEast** [comment]
@avivbeeri Just merged a PR that adds this functionality (#138)! It available now on Github, or otherwise soon with the next Ogmo release 👍
