### ISSUE TITLE
Add Nodes Between Existing Nodes.

### ISSUE THREAD

**Issue by raeleus** [Ogmo-Editor-3/OgmoEditor3-CE#117]
There currently is no way to add nodes between existing nodes in a path. You can add nodes to the end and modify/delete existing nodes, but there is no way add a new node between existing ones. This proves to be frustrating when you are using nodes to define something like terrain or a collision map.

A solution can be to add a transparent preview when the user hovers over a path with the Add Node tool. This will keep the interface simple and make the feature obvious. This would not apply to entities with a Fan or None node setting.

Thank you for the great tool!

**Comment by AustinEast** [comment]
ive been working with nodes in a project recently.. i agree it needs some TLC!

**Comment by raeleus** [comment]
I was still able to complete my jam game using nodes: https://raeleus.itch.io/vtol-vertical-take-off-and-landing
If you see the level design, you can see what a pain it would be to make adjustments. I basically had to create a new entity every time I needed to make an adjustment. Nevertheless, I couldn't have done it without this excellent editor!

**Comment by AustinEast** [comment]
@raeleus this feature is added with #156
