### ISSUE TITLE
Defaults for Level Values are not Saved

### ISSUE THREAD

**Issue by raeleus** [Ogmo-Editor-3/OgmoEditor3-CE#118]
If you create a new level value for the project, you have the option to set a default. If you set a default, hit save, and then click edit project, you'll notice the default is not there. The defaults are not applied to the levels either. Thank you for looking into this.

**Comment by 01010111** [comment]
I notice if I set the default and click onto another level value, the first one gets saved

**Comment by AustinEast** [comment]
@raeleus fixed with #147 👍
