### ISSUE TITLE
Show ID of an entity when selected

### ISSUE THREAD

**Issue by danigatts** [Ogmo-Editor-3/OgmoEditor3-CE#124]
There is one feature missing from OgmoEditor 2 in which you can get the ID of an entity when you select it. This is useful to link entities: for example, to store an item inside a crate, you'll define a custom value for the crate with the ID of the item it contains. Currently there is no way to obtain this ID unless you look at the generated JSON file.

**Comment by AustinEast** [comment]
Not a bad idea! adding the enhancement label, hopefully someone can get to this sooner than later.

**Comment by AustinEast** [comment]
closed with #132
