### ISSUE TITLE
Resizable entity height can't be changed after width

### ISSUE THREAD

**Issue by TheSpydog** [Ogmo-Editor-3/OgmoEditor3-CE#126]
Steps to reproduce:
1. Create a project with an entity layer
2. Create an entity with Resizable X and Resizable Y
3. Place that entity in a level
4. Change its Width to 32. Notice the change.
5. Change its Height to 32. Notice there's no change.
6. Reset width/height to 16.
7. Edit Height to 32. Notice the change.
8. Edit Width to 32. Notice the change.

This is a weird one... Why does the order matter here? I'll dig into this sometime soon.

**Comment by AustinEast** [comment]
closed with #146
