### ISSUE TITLE
[Feature Request] Tile Flip Vertical, Flip Horizontal, Rotation 90 degress

### ISSUE THREAD

**Issue by damarindra** [Ogmo-Editor-3/OgmoEditor3-CE#128]
Allowing this with some shortcut key is really helpful.

**Comment by AustinEast** [comment]
this does sound like a good feature, but we'd have to figure out a way to store each placed tile's orientation when saving/exporting to json. 

I'll think on how this could work, but any suggestions would be great! (not directing that request specifically at you though haha)

**Comment by damarindra** [comment]
haha, take your time dude. I want to contribute, but I never touch haxe, so I'll pass it. Yes, I'm quite wondering too, how to save that info in json file, since I've created importer for MonoGame.

**Comment by AustinEast** [comment]
Tile Flipping/Rotation has been added with #135. the next step will be adding some documentation to the [manual](https://github.com/Ogmo-Editor-3/Ogmo-Editor-3.github.io)!

**Comment by damarindra** [comment]
Yaaayy
