### ISSUE TITLE
I'm not able to compile the project

### ISSUE THREAD

**Issue by edwinsyarief** [Ogmo-Editor-3/OgmoEditor3-CE#133]
Hi all,

I've just pull the latest update, and now when I'm trying to npm i, npm run build, the build not successfull, it says module not found 'spawn-sync'.

Please help

**Comment by TheSpydog** [comment]
Hi, I just tested on my machine and I'm seeing the exact same thing. This must have changed recently since I was able to build without issue a couple weeks ago. Unfortunately I know basically nothing about the npm ecosystem so I'm not sure what to suggest. :(

@AustinEast any ideas?

**Comment by AustinEast** [comment]
Weird.. just tested, and im still able to compile and run on my Mac. I am seeing your error, but as only a warning:

<img width="1359" alt="Screen Shot 2020-06-15 at 2 41 14 PM" src="https://user-images.githubusercontent.com/9554269/84694050-855fa280-af16-11ea-8fdc-9fa3134b4b50.png">

Ill try it out on my windows box when I can and see if I hit any issues there

**Comment by edwinsyarief** [comment]
Okay, I just updated the nodejs as suggested by vontoGH, and I'm able to build the project successfully
