### ISSUE TITLE
i made a Ogmo editor win32 binary version

### ISSUE THREAD

**Issue by vontoGH** [Ogmo-Editor-3/OgmoEditor3-CE#134]
Hi, 
since i had a few requests and didn't know where to post :

[Ogmo editor win32 binary version ](https://github.com/vontoGH/OgmoEditor3-CE/releases/tag/3.3.0)

**Comment by edwinsyarief** [comment]
Hi,

Is this the latest version from git?

Thanks

**Comment by vontoGH** [comment]
It's based on the official 3.3.0 package.

**Comment by edwinsyarief** [comment]
@vontoGH can you build the latest version from git? Mine is always error at 'spawn-sync' things

**Comment by vontoGH** [comment]
same here, i cannot even compile the version i uploaded anymore. It seems some updates in npm or node broke the toolchain :(

**Comment by vontoGH** [comment]
OK, done. I just updated node to the latest (14.4.0) not the LTS
will post a new release.

**Comment by edwinsyarief** [comment]
@vontoGH thank you for the information, my issue is fixed 😄

**Comment by 01010111** [comment]
@vontoGH thanks! can you give us some info on how to build for win32? In the future we may be able to automate this for new releases :)

**Comment by vontoGH** [comment]
@01010111 i used a windows 10 32 bits machine and i followed the build instructions you provide (with the latest nodejs).

**Comment by AustinEast** [comment]
@vontoGH if you don't mind, I'd like to add a link to your releases page on Ogmo's README. that way we can close this issue + make the link more visible until we figure out a more permanent solution 😁

**Comment by vontoGH** [comment]
@AustinEast : do it.

i just made a new version : [Ogmo Editor CE win32  june edition](https://github.com/vontoGH/OgmoEditor3-CE/releases/tag/v3.3.0-20-06-24)

**Comment by AustinEast** [comment]
awesome. doing it now 👍
