### ISSUE TITLE
Unable to close the application

### ISSUE THREAD

**Issue by edwinsyarief** [Ogmo-Editor-3/OgmoEditor3-CE#154]
I have an issue with the latest version from git. After I opened the application, I'm not able to close the application, the only way is to kill it from task manager.

Or it is just issue with my laptop?

Thank you.

**Comment by Ohmnivore** [comment]
Can repro.
I must have introduced a bug in https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/pull/139
I'll take a look.

**Comment by AustinEast** [comment]
@edwinsyarief i just merged a potential fix (#155). let us know if that fixes your issue!

**Comment by edwinsyarief** [comment]
Hi, this issue is fixed. Thank you very much.
