### ISSUE TITLE
JSON formats documentation

### ISSUE THREAD

**Issue by mariusvn** [Ogmo-Editor-3/OgmoEditor3-CE#184]
Hello,
I'm working on a game and I use OGMO as tile editor.
I had some troubles to understand all JSON output keys like in the level json: `tileFlags2d`.
I know that it's handling the rotation of the tiles but I don't know what the content means.

My main request is to have a JSON format documentation.
I know that there was one before because I used it in the past.

Thanks,

Marius

**Comment by AustinEast** [comment]
Hey! We have some in-progress docs in the Website repo (check out [this comment](https://github.com/Ogmo-Editor-3/Ogmo-Editor-3.github.io/issues/11#issuecomment-594769301)) - They just need someone with to finish them, but I haven't  had the free time these days to do it myself unfortunately.
