### ISSUE TITLE
Allow using images to represent entities

### ISSUE THREAD

**Issue by tesselode** [Ogmo-Editor-3/OgmoEditor3-CE#46]
As far as I can tell, entities can only be colored squares, which is not a great way to keep track of what's what. It would be nice to be able to use an image or a tile from an existing tileset to draw the entity.

**Comment by AustinEast** [comment]
just added in a field to upload a texture to be used for the entity with the release of 3.1.0 👍

**Comment by 01010111** [comment]
@AustinEast @tesselode this looks like it's completed? Should I close this issue or do we want to add more to it (specifically what comes to mind is using the preview image in the entity palette)

**Comment by AustinEast** [comment]
yeah, I left it open since I was unsure how far to take the issue. let me see if I can update the palette images, then ill close 👍

**Comment by AustinEast** [comment]
finished with commit 1a38f52c5e950b10e4ed6983571e86da990dca81
