### ISSUE TITLE
Show an image preview instead of an error when clicking an image file in the sidebar

### ISSUE THREAD

**Issue by tesselode** [Ogmo-Editor-3/OgmoEditor3-CE#47]
![image](https://user-images.githubusercontent.com/2637802/68983744-6b23e180-07da-11ea-9790-1c174e68f018.png)

A preview of the image would be much nicer here.

**Comment by AustinEast** [comment]
<img width="1253" alt="Screen Shot 2019-11-15 at 8 39 44 PM" src="https://user-images.githubusercontent.com/9554269/68985916-2bfc8d00-07e8-11ea-8a8b-a4ed6e1cd727.png">

just added in better file handling with commit 77f933ccc86f64bc628575d695454ef44caf5b95!

ill see what I can do about #46, then update the binary on itch. 👍

**Comment by tesselode** [comment]
very nice!

**Comment by AustinEast** [comment]
alrighty, just fixed this issue with the release of 3.1.0.
