### ISSUE TITLE
Add "random tiles" checkbox

### ISSUE THREAD

**Issue by codecat** [Ogmo-Editor-3/OgmoEditor3-CE#51]
When selecting multiple tiles from a tileset, it would be nice to be able to "randomize" which tile gets placed when using any of the tile-placing tools.

**Comment by TheSpydog** [comment]
This feature already exists! You can randomize tiles by holding Ctrl as you draw. 🙂 In the docs: https://ogmo-editor-3.github.io/docs/#/manual/tile-layers.md

**Comment by codecat** [comment]
Oh! Cool. Totally missed that! Maybe this can be made more clear in the UI somewhere? Just my 2 cents. 👍
