### ISSUE TITLE
Add the ability to change default grid size

### ISSUE THREAD

**Issue by 01010111** [Ogmo-Editor-3/OgmoEditor3-CE#55]
Right now everything defaults to 8x8 - it'd be nice to have the option to change that default, maybe we can work it into the tilemap settings dialog?:
User inputs tile size -> Clicks "Make Default Grid Size"

**Comment by AustinEast** [comment]
sounds good to me - in addition from being able to set it in the general project editor. we should be able to get this in for 3.2 :)

**Comment by AustinEast** [comment]
Just added the setting into the general project panel with commit 50a852a2dd3abfca71ec8683a665f61b0a28a229.

I didn't add anything into the new layer dialog like you were saying though, @01010111. How attached are you to that idea? :P

**Comment by 01010111** [comment]
@AustinEast yeah I think holding off on that until later would be fine!
