### ISSUE TITLE
Automatically update all level files with edited Project data

### ISSUE THREAD

**Issue by 01010111** [Ogmo-Editor-3/OgmoEditor3-CE#58]
We'd have to validate them before doing so in case people have other JSON files in their directories - we could either look for specific schemas or just maybe tag level JSONs with something like 
```
"ogmo_version": 3.2
```
and just look for that?

**Comment by 01010111** [comment]
From Austin in Discord:
> so im thinking we could add a button to the project editor that says "Save & Update", which will go through your project and automatically update levels (basically open them then resave so they get updated with the new values).

> i wouldnt want to have that be the default behaviour tho, incase you have legacy levels that you dont want to update with the rest of your project, so we could keep the regular "Save" button too.

**Comment by AustinEast** [comment]
i was thinking about adding some metadata like `ogmo_version` into the exported stuff, so im on board with that 👍

**Comment by 01010111** [comment]
I'll add an issue for that - let's get that in the next version so that it can help down the road as much as possible!
