### ISSUE TITLE
Serialize custom values as correct data type

### ISSUE THREAD

**Issue by 01010111** [Ogmo-Editor-3/OgmoEditor3-CE#65]
right now they all serialize to strings

**Comment by deepnight** [comment]
It might break a few existing things, no? 
I subbed to this issue to update my libs on time. 👍

**Comment by 01010111** [comment]
Yeah - so maybe we ought to prioritize this issue to get it done ASAP if we want to do it!

**Comment by 01010111** [comment]
@deepnight ☝️ not rolled out to a release yet, but the change was made!

**Comment by deepnight** [comment]
I'll update my libs tomorrow, you can roll out whenever that's ok for you :)
