### ISSUE TITLE
Pressing ENTER in a Text edit popup adds a newline AND closes it 

### ISSUE THREAD

**Issue by deepnight** [Ogmo-Editor-3/OgmoEditor3-CE#71]
Steps to reproduce:

 - create an Entity with a Custom Value: type Text, name "foo"
 - add an instance of this entity to a layer
 - edit the instance Custom Value "foo"
 - hitting ENTER adds a new line (cool), but also closes the popup (not cool)

**Comment by 01010111** [comment]
As a stop-gap we should at least make sure `SHIFT+ENTER` only adds a new line

**Comment by deepnight** [comment]
The text editor there being some sort of TextArea, the logic would normally be: Enter > new line, Shift+ENTER > close popup 🤔

**Comment by 01010111** [comment]
I think it's more common that `SHIFT+ENTER` means new line - Ideally I think we would make `CTRL+ENTER` be the shortcut to confirming text entry, but I haven't looked into the level of effort of doing that just for this modal - it might be easy for all I know :)

**Comment by 01010111** [comment]
Throwing this out there - would we be ok with NO shortcut key to confirm? (as in - pressing ENTER would NEVER close a text box)

**Comment by 01010111** [comment]
Fixed with b651527
