### ISSUE TITLE
Reloading or Editing project settings creates a new Unsaved level

### ISSUE THREAD

**Issue by deepnight** [Ogmo-Editor-3/OgmoEditor3-CE#72]
When pressing the ♻️ **Reload** button, or **Edit Project**, the editor opens a new Unsaved Level.

Expected behavior:
 - re-open the last opened map
 - re-select the last active layer

**Comment by AustinEast** [comment]
We're looking to resolve this with #34 👍

**Comment by 01010111** [comment]
I'm going to go ahead and close this bc it's a duplicate of #34
