### ISSUE TITLE
fields in the project editor don't reset after discarding changes

### ISSUE THREAD

**Issue by tesselode** [Ogmo-Editor-3/OgmoEditor3-CE#83]
If you make changes to fields in the project editor, and then cancel instead of saving changes, the fields will not be reset by the time you re-open the project editor.

**Comment by 01010111** [comment]
Are you unable to do this?
![ezgif-6-7fa47c842501](https://user-images.githubusercontent.com/1042453/69349462-c411d080-0c45-11ea-94e2-918e7ce07400.gif)

**Comment by tesselode** [comment]
update: this bug only happens after the first time you save a project. see #82

**Comment by AustinEast** [comment]
I believe this should be fixed with commit af014e0
