### ISSUE TITLE
Versioning and compatibility

### ISSUE THREAD

**Issue by Geokureli** [Ogmo-Editor-3/OgmoEditor3-CE#86]
Since many people are going to want to convert over to OE3-CE, would it make sense to allow OGMO to load, identify and convert older versions of OGMO files? On that note, does it make sense to start including the version number in levels created for conversion to future versions once breaking changes are made to the software?

**Comment by 01010111** [comment]
added with https://github.com/Ogmo-Editor-3/ogmo-conv/tree/master
