### ISSUE TITLE
[Request] Include folder path in decal layers

### ISSUE THREAD

**Issue by Geokureli** [Ogmo-Editor-3/OgmoEditor3-CE#88]
I don't really have an elegant way to specify a corresponding parent folder to each decal layer in my game's ogmo parser, it seems like it should be included in the json and not just the .ogmo project file.

**Comment by AustinEast** [comment]
im normally against adding things to the exported level json that can be referenced from the project file (to keep the project file as a single "source of truth"), but if you change the decal layer's "image folder" in your project, it'll just end up invalidating the all the decal texture paths in your levels anyways. so I think this is a good addition 👍

**Comment by AustinEast** [comment]
added with commit 27b3fd7afdf922ca4d08eb5691191e5f832eff36
