### ISSUE TITLE
Mac/Win paths

### ISSUE THREAD

**Issue by Geokureli** [Ogmo-Editor-3/OgmoEditor3-CE#89]
I get borked levels when my mac opens up files that were saved using windows `foo\\bar` paths
<img width="481" alt="Screen Shot 2019-12-02 at 11 10 30 PM" src="https://user-images.githubusercontent.com/2609513/70066069-adf30100-15b1-11ea-8afe-0b1c50e2e58d.png">

**Comment by AustinEast** [comment]
would it be best to normalize the exported filepath values to `foo/bar` for all platforms?

**Comment by TheSpydog** [comment]
I think that makes the most sense.
