### ISSUE TITLE
Tileset parsing

### ISSUE THREAD

**Issue by sponge** [Ogmo-Editor-3/OgmoEditor3-CE#94]
Since the file format documentation currently links back to the index since I assume it's incomplete, I've been trying to figure out what is the intent for how a game should load levels. Should the JSON levels be completely self-contained, or does a game need to parse the .ogmo file in addition to the current level?

In the case I noticed, the exported level only contains the tileset name, and not the path to the tileset. Since there's no link from the level back to the .ogmo file I can't load levels by loading the level's JSON file, I need to load an .ogmo file that is provided in advance. This doesn't feel correct, since there seems to be some duplicate data that is updated when you load a level and then resave it.

**Comment by AustinEast** [comment]
Does the new external scripting functionality cover this use case for you?

**Comment by sponge** [comment]
It does! It was just a one-liner, I should've included it in the docs, but if you wanted to put it in the level save, it's just
`        layer.tilesetPath = project.tilesets.find(ts => ts.label === layer.tileset).path;`
