### ISSUE TITLE
Entity booleans are saved as string

### ISSUE THREAD

**Issue by sponge** [Ogmo-Editor-3/OgmoEditor3-CE#95]
It looks like entities with custom boolean fields get exported as strings, instead of boolean values, eg `"values": {"is a thing": "true", "new_value": "0"}` instead of an actual boolean value. This is potentially annoying since if I'm parsing levels using a C library, I have to compare the string value against true or false strings, instead of just grabbing a boolean directly.

**Comment by 01010111** [comment]
The next version should fix this issue with #77 !

**Comment by deepnight** [comment]
Any estimate about a PR? Latest git version breaks a few things in the interface and bools are not usable anymore for now :/
