### ISSUE TITLE
Backspace in entity inspector deletes the entity

### ISSUE THREAD

**Issue by DaedalusGame** [Ogmo-Editor-3/OgmoEditor3-CE#97]
I kind of expected it to only delete one character in the textbox but it actually deleted the entity

**Comment by AustinEast** [comment]
Make sure the textfield has focus when you hit backspace. It looks like the inspector textfields can be a little finicky on keeping focus when your mouse leaves them, so that should probably be fixed.

**Comment by DaedalusGame** [comment]
actually yeah the textfield loses focus when the mouse moves one pixel after selection unless you're in create mode

**Comment by AustinEast** [comment]
gotcha! i haven’t been able to figure out exactly when it was being weird, so that’s a start. ill try to look into this asap
