### ISSUE TITLE
It's no longer possible to expand enum values in Entity inspector

### ISSUE THREAD

**Issue by deepnight** [Ogmo-Editor-3/OgmoEditor3-CE#99]
Tested on Ogmo 3.2.1 from itch.io.

Clicking on an enum value immediately opens & closes the enum value list.
You can see a video of the issue in action in this video:

[enumBug.zip](https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/files/3951860/enumBug.zip)

**Comment by AustinEast** [comment]
this is most likely related to #97. I'm planning on looking into it today 👍

**Comment by AustinEast** [comment]
Im having trouble reproducing on Mac, so Im wondering if this is just a Windows thing..
